RULES = (
    "Перед началом прочитайте правила:\n\n"
    "1. Вам есть 18 лет.\n"
    "2. Бот только добавляет актёров на фото. Никакой эротики и раздевания.\n"
    "3. Вы загружаете фото людей только с их разрешения и отвечаете за это сами.\n"
    "4. Результат — развлекательный монтаж, не выдавайте его за реальность.\n\n"
    "Нажимая «Принимаю», вы подтверждаете всё выше."
)
RULES_ACCEPT_BTN = "✅ Принимаю"
RULES_REQUIRED = "Сначала примите правила: /start"
WELCOME = "Готово! Вам начислено {n} кристалликов 💎\n\nЧто делаем?"
MENU = "Главное меню"

BTN_CREATE = "📸 Создать фото"
BTN_BALANCE = "💎 Баланс"
BTN_SHOP = "🛒 Магазин"
BTN_BONUS = "🎁 Забрать бонус"
BTN_HELP = "❓ Помощь"
BTN_BACK = "◀️ Назад"
BTN_SKIP = "Пропустить"
BTN_NO = "Нет, дальше"
BTN_YES_PHOTO = "Да, пришлю фото"
BTN_CUSTOM_SCENE = "✏️ Своя сцена"
BTN_GENERATE = "🚀 Сгенерировать"
BTN_CANCEL = "Отмена"
BTN_PREV = "⬅️"
BTN_NEXT = "➡️"
BTN_MORE = "🔁 Ещё вариант"
BTN_CHANGE_SCENE = "🎬 Сменить сцену"
BTN_CHANGE_ACTOR = "⭐ Сменить актёра"
BTN_NEW_PHOTO = "🆕 Новое фото"

HELP = (
    "Как это работает:\n"
    "1. Пришлите фото человека (можно двух).\n"
    "2. Выберите актёра (можно двух).\n"
    "3. Выберите сцену или опишите свою.\n"
    "4. Получите фото.\n\n"
    "Каждая генерация стоит кристаллики. Бонус можно забирать кнопкой в меню."
)

SEND_PERSON_1 = "Пришлите фото человека. Лицо должно быть хорошо видно."
SEND_PERSON_2 = "Пришлите фото второго человека."
NO_FACE = "На фото не нашёл лица. Пришлите другое, где лицо видно крупнее."
NOT_A_PHOTO = "Нужно фото. Пришлите картинку."
ASK_PERSON_2 = "Добавить второго человека?"
CHOOSE_ACTOR = "Выберите актёра:"
ASK_ACTOR_2 = "Добавить второго актёра?"
CHOOSE_ACTOR_2 = "Выберите второго актёра:"
CHOOSE_SCENE = "Выберите сцену:"
CATALOG_EMPTY = "Каталог актёров пока пуст. Попробуйте позже."
CUSTOM_SCENE_PROMPT = "Опишите сцену текстом (до 200 символов) или пришлите фото места."
CUSTOM_SCENE_TOO_LONG = "Слишком длинно. До 200 символов."
ASK_DETAIL = "Добавить свою деталь? Например: «зимой, в пальто». Или нажмите «Пропустить»."
DETAIL_TOO_LONG = "Слишком длинно. До 100 символов."
TEXT_REJECTED = "Такое не сделаем. Напишите иначе, без эротики."
CHOOSE_MODEL = "Выберите качество:"
MODEL_BASE_BTN = "Обычное — {cost} 💎"
MODEL_PREMIUM_BTN = "Премиум — {cost} 💎"
MODEL_PREMIUM_LOCKED = "Премиум доступен по подписке"
CONFIRM = (
    "Проверьте:\n"
    "👤 Людей: {people}\n"
    "⭐ Актёры: {actors}\n"
    "🎬 Сцена: {scene}\n"
    "✨ Деталь: {detail}\n"
    "🖼 Качество: {model}\n\n"
    "Спишется {cost} 💎. Баланс: {balance} 💎"
)
NOT_ENOUGH = "Не хватает кристалликов: нужно {cost}, у вас {balance}. Загляните в магазин 🛒"
GENERATING = "Генерирую, около 20 секунд ⏳"
ALREADY_RUNNING = "Предыдущая генерация ещё в работе, подождите."
GEN_FAILED = "Не получилось сгенерировать. Кристаллики вернули, попробуйте ещё раз."
GEN_REJECTED = "Результат не прошёл проверку контента. Кристаллики вернули, измените запрос."
SESSION_EXPIRED = "Сессия истекла, загрузите фото заново."
RESULT_CAPTION = "{actors} · {scene}"
RESULT_SEND_FAILED = "Фото готово, но отправить не удалось. Нажмите «Ещё вариант»."
GENERIC_ERROR = "Что-то пошло не так. Попробуйте ещё раз."
CANCELLED = "Отменено."

BALANCE = (
    "💎 Кристаллики: {crystals}\n"
    "⭐ Подписка: {sub}\n"
    "🎁 Бонус: {bonus}"
)
SUB_NONE = "нет"
SUB_ACTIVE = "{plan} до {until}"
BONUS_READY = "готов, нажмите «Забрать бонус»"
BONUS_WAIT = "через {hours} ч {minutes} мин"
BONUS_CLAIMED = "+{n} 💎 за вход! Баланс: {balance} 💎"
BONUS_NOT_READY = "Бонус ещё не готов. Приходите {when}."

SHOP = "Выберите пакет или подписку:"
PACK_BTN = "{n} 💎"
SUB_BTN = "Подписка {name}"
PAY_CHOOSE = "{title}\n\nКак оплатить?"
BTN_PAY_CARD = "💳 Оплатить картой"
BTN_PAY_STARS = "⭐ Оплатить в Stars"
BTN_BUY_STARS = "🇷🇺 Купить Stars по РУ-карте"
PAY_CARD_HINT = "Оплата откроется в Tribute. После оплаты кристаллики придут автоматически."
PAYMENT_OK_PACK = "Оплата прошла! +{n} 💎. Баланс: {balance} 💎"
PAYMENT_OK_SUB = "Подписка активна до {until}. Спасибо!"
PRODUCT_NOT_CONFIGURED = "Этот способ оплаты пока не настроен."

PLAN_NAMES = {"sub_week": "неделя", "sub_month": "месяц", "sub_3month": "3 месяца"}
MODEL_NAMES = {"base": "обычное", "premium": "премиум"}

CUSTOM_SCENE_LABEL_TEXT = "своя (текст)"
CUSTOM_SCENE_LABEL_PHOTO = "своя (фото)"
DETAIL_NONE = "нет"

ADMIN_ONLY = "Только для админов."

ADM_STATS = (
    "📊 Сегодня / 7 дней\n"
    "Новые пользователи: {u1} / {u7}\n"
    "Генерации (обычн/премиум): {g1b}/{g1p} / {g7b}/{g7p}\n"
    "Расход Runware: ${c1:.2f} / ${c7:.2f}\n"
    "Stars: {s1} / {s7}\n"
    "Tribute, руб: {t1} / {t7}"
)
ADM_USAGE_GIVE = "Формат: /give <user_id> <n>"
ADM_USAGE_SUB = "Формат: /sub <user_id> <sub_week|sub_month|sub_3month>"
ADM_USAGE_USER = "Формат: /user <user_id>"
ADM_USAGE_BLOCK = "Формат: /block <user_id>"
ADM_BLOCK_OK = "Пользователь {uid} заблокирован."
ADM_UNBLOCK_OK = "Пользователь {uid} разблокирован."
ADM_USER_NOT_FOUND = "Пользователь не найден."
ADM_GIVE_OK = "Начислено {n} 💎 пользователю {uid}. Баланс: {balance}"
ADM_SUB_OK = "Подписка {plan} пользователю {uid} до {until}"
ADM_USER_CARD = "👤 {uid} @{username}\n💎 {crystals}\n⭐ {sub}\n🖼 Генераций: {gens}\n📅 С {created}"
ADM_ACTORS = "Актёры:"
ADM_SCENES = "Сцены:"
ADM_ADD = "➕ Добавить"
ADM_BACK = "◀️ К списку"
ADM_TOGGLE = "Вкл/Выкл"
ADM_DELETE = "🗑 Удалить"
ADM_SHOW_REFS = "🖼 Фото"
ADM_ACTOR_NAME = "Имя актёра для кнопки:"
ADM_ACTOR_DESC = "Описание внешности для промпта (лучше по-английски, до 200 символов):"
ADM_ACTOR_PHOTOS = "Пришлите 2–4 фото по одному. Когда хватит, нажмите «Готово»."
ADM_ACTOR_PHOTO_OK = "Принято {n}/4."
ADM_ACTOR_NEED_MORE = "Нужно минимум 2 фото."
ADM_DONE = "✅ Готово"
ADM_ACTOR_CREATED = "Актёр «{name}» добавлен."
ADM_SCENE_NAME = "Название сцены для кнопки:"
ADM_SCENE_PROMPT = "Описание сцены для промпта (по-английски, до 300 символов):"
ADM_SCENE_ORIENT = "Ориентация кадра:"
ADM_PORTRAIT = "Вертикальная"
ADM_LANDSCAPE = "Горизонтальная"
ADM_SCENE_PHOTO = "Пришлите фото места или нажмите «Без фото»."
ADM_NO_PHOTO = "Без фото"
ADM_SCENE_CREATED = "Сцена «{name}» добавлена."
ADM_TEXT_REJECTED = "Описание не прошло стоп-лист."
ADM_DELETED = "Удалено."
ADM_TOO_LONG = "Слишком длинно."

INVOICE_DESC_PACK = "+{n} кристалликов"
INVOICE_DESC_SUB = "{days} дней подписки"
