RULES = (
    "Перед началом прочитайте правила:\n\n"
    "1. Вам есть 18 лет.\n"
    "2. Бот только добавляет актёров на фото. Никакой эротики и раздевания.\n"
    "3. Вы загружаете фото людей только с их разрешения и отвечаете за это сами.\n"
    "4. Результат — развлекательный монтаж, не выдавайте его за реальность.\n\n"
    "Нажимая «Принимаю», вы подтверждаете всё выше."
)
RULES_ACCEPT_BTN = "✅ Принимаю"
RULES_REQUIRED = "Сначала прими правила: /start"
WELCOME = "Готово! Тебе упало {n} 💎\n\nКидай фото — и подберём звезду 😉"
MENU = "Что делаем?"
INTRO = (
    "🌟 <b>Фото со звездой за 20 секунд</b>\n\n"
    "Кидаешь фото → выбираешь актёра → получаешь снимок, будто вы правда стояли рядом.\n\n"
    "<b>Что умею:</b>\n"
    "📸 Ставлю тебя рядом со звездой\n"
    "🎬 Меняю сцену: яхта, клуб, красная дорожка, Париж…\n"
    "👥 Добавляю второго человека или второго актёра\n"
    "✏️ Дорисовываю твою деталь: «зимой, в пальто»\n\n"
    "💎 Одно фото — 1 кристаллик. Бонус каждый день."
)
BTN_INTRO_CREATE = "📸 Сделать фото со звездой"
BTN_INTRO_PROFILE = "👤 Профиль"
BTN_INTRO_BONUS = "🎁 Бонус"
BTN_INTRO_HELP = "❓ Как это работает"

BTN_CREATE = "📸 Создать фото"
BTN_PROFILE = "👤 Профиль"
BTN_HELP = "❓ Помощь"
BTN_ADD_PERSON = "➕ Добавить человека с фото"
BTN_CUSTOM_SCENE = "✏️ Своя сцена"
BTN_DETAIL = "✏️ Своя деталь"
BTN_CANCEL = "Отмена"
BTN_PREV = "⬅️"
BTN_NEXT = "➡️"
BTN_MORE = "🔁 Ещё вариант"
BTN_RANDOM_SCENE = "🎲 Другая сцена"
BTN_CHANGE_SCENE = "🎬 Выбрать сцену"
BTN_CHANGE_ACTOR = "⭐ Другой актёр"
BTN_ADD_ACTOR = "➕ Ещё актёр"
BTN_ADD_PERSON_RESULT = "➕ Добавить человека"
BTN_NEW_PHOTO = "🆕 Новое фото"

HELP = (
    "<b>Как это работает</b>\n"
    "1. Кидаешь фото — своё или друга.\n"
    "2. Выбираешь звезду.\n"
    "3. Через 20 секунд получаешь готовый снимок.\n\n"
    "<b>⭐ Звёзды</b>\n{actors}\n\n"
    "<b>🎬 Сцены</b>\n{scenes}\n\n"
    "<b>🕺 Позы</b>\n"
    "Позу задаёшь кнопкой «✏️ Своя деталь» под фото: «обнимаемся», «даём пять», "
    "«смотрим друг на друга», «стоим спина к спине», «показываем сердечко руками».\n\n"
    "Под фото ещё кнопки: другая сцена, другой актёр, ещё человек, новое фото.\n"
    "💎 Кристаллики и качество — в профиле."
)
HELP_ACTORS_MORE = "{names} и ещё {n}"
HELP_SCENES_MORE = "{names} и ещё {n}"
HELP_ACTORS_NONE = "скоро появятся"

SEND_PERSON_1 = "Кинь фото человека. Лицо покрупнее — и поехали 🚀"
SEND_PERSON_2 = "Кинь фото второго. Лицо тоже покрупнее."
NO_FACE = "Лица не вижу 🙈 Кинь другое, где лицо крупнее."
NOT_A_PHOTO = "Нужно именно фото 📷 Кинь картинку."
CHOOSE_ACTOR = "С кем фоткаемся? ⭐"
CHOOSE_ACTOR_2 = "И кого добавим вторым?"
CHOOSE_SCENE = "Где фоткаемся? 🎬"
CATALOG_EMPTY = "Звёзды ещё едут 🚗 Загляни чуть позже."
CUSTOM_SCENE_PROMPT = "Опиши сцену парой слов (до 200 символов) или кинь фото места."
CUSTOM_SCENE_TOO_LONG = "Длинновато 😅 До 200 символов."
ASK_DETAIL = "Какую деталь добавить? Например: «зимой, в пальто»."
DETAIL_TOO_LONG = "Длинновато 😅 До 100 символов."
TEXT_REJECTED = "Такое не делаем 🙅 Напиши иначе."
MODEL_PREMIUM_LOCKED = "Премиум-качество открывается с подпиской ⭐"
NOT_ENOUGH = "Не хватает кристалликов: нужно {cost}, у тебя {balance}."
NOT_ENOUGH_HINT = "Кристаллики — в профиле 👤"
GENERATING = "Колдую… секунд 20 ⏳"
ALREADY_RUNNING = "Ещё колдую над прошлым фото, секунду ⏳"
GEN_FAILED = "Не вышло 😔 Кристаллики вернул, попробуй ещё раз."
GEN_REJECTED = "Такое не делаем 🙅 Кристаллики вернул, попробуй иначе."
SESSION_EXPIRED = "Фото уже улетело из памяти 🙈 Кинь заново."
RESULT_CAPTION = "{actors} · {scene}\nНе то? Жми кнопки 👇"
RESULT_SEND_FAILED = "Фото готово, но не долетело. Жми «Ещё вариант»."
GENERIC_ERROR = "Что-то пошло не так 😔 Попробуй ещё раз."
CANCELLED = "Ок, отменил."

PROFILE = "👤 Профиль\n\n💎 Кристаллики: {crystals}\n⭐ Подписка: {sub}\n🎁 Бонус: {bonus}\n🖼 Качество: {quality}\n\n{quality_costs}"
BTN_QUALITY_TOGGLE = "🖼 Качество: {quality} → {other}"
BTN_QUALITY_LOCKED = "🖼 Премиум-качество — по подписке"
QUALITY_COSTS = "Обычное — {base} 💎, премиум — {premium} 💎 за фото."
SUB_NONE = "нет"
SUB_ACTIVE = "{plan} до {until}"
BONUS_READY = "готов, забирай 🎁"
BONUS_WAIT = "через {hours} ч {minutes} мин"
BONUS_CARD = "🎁 Тебе прилетел бонус: +{n} 💎\nЗабирай кнопкой ниже."
BTN_BONUS_CLAIM = "🎁 Забрать бонус"
BONUS_CLAIMED = "+{n} 💎 за вход! Баланс: {balance} 💎"
BONUS_NOT_READY = "Бонус ещё зреет 🌱 Приходи {when}."

BTN_BUY_PACK = "💎 Купить пакет"
BTN_BUY_SUB = "⭐ Подписка"
SHOP_PACKS = (
    "💎 <b>Кристаллики</b>\n\n"
    "1 кристаллик = 1 фото со звездой.\n"
    "Премиум-качество = {premium} кристаллика за фото.\n"
    "Не сгорают и не ограничены по времени.\n\n"
    "💳 Оплата: СБП, карта или Telegram Stars.\n\n"
    "Выбирай пакет:"
)
SHOP_SUBS = (
    "⭐ <b>Звёздная подписка</b>\n\n"
    "Что даёт:\n"
    "🎁 {daily} кристалликов каждый день — забирай кнопкой в профиле\n"
    "🖼 Премиум-качество: лица как живые, без «пластилина»\n"
    "🎬 Все сцены, все звёзды, без ограничений\n"
    "⚡ Это до {daily} фото в день и до {monthly} в месяц\n"
    "🎉 Плюс подарок сразу при покупке: 10, 50 или 200 кристалликов\n\n"
    "💳 Оплата: СБП, карта или Telegram Stars.\n\n"
    "Выбирай срок:"
)
PACK_BTN = "{n} 💎"
SUB_BTN = "{name} · +{gift} 💎 в подарок"
PRICE_RUB = "{rub} ₽"
PRICE_STARS = "{stars} ⭐"
PRICE_BOTH = "{rub} ₽ / {stars} ⭐"
PAY_CHOOSE_PACK = (
    "💎 <b>{title}</b>\n"
    "{n} фото со звёздами, кристаллики не сгорают.\n\n"
    "Выбери способ оплаты:"
)
PAY_CHOOSE_SUB = (
    "⭐ <b>{title}</b>\n"
    "🎁 {daily} кристалликов в день · 🖼 премиум-качество · 🎬 все сцены и звёзды\n"
    "🎉 Сразу в подарок: +{gift} 💎\n\n"
    "Выбери способ оплаты:"
)
BTN_PAY_CARD = "💳 СБП / карта{price}"
BTN_PAY_STARS = "⭐ Звёзды — {stars} ⭐"
BTN_BUY_STARS = "🇷🇺 Купить звёзды по РУ-карте"
PAYMENT_OK_PACK = "Оплата прошла! +{n} 💎. Баланс: {balance} 💎"
PAYMENT_OK_SUB = "Подписка активна до {until} ⭐\nВ подарок +{n} 💎, баланс: {balance} 💎"
PRODUCT_NOT_CONFIGURED = "Этот способ оплаты пока не настроен."

PRODUCT_TITLES = {
    "pack_50": "50 кристалликов",
    "pack_100": "100 кристалликов",
    "pack_300": "300 кристалликов",
    "sub_week": "Подписка на неделю",
    "sub_month": "Подписка на месяц",
    "sub_3month": "Подписка на 3 месяца",
}
PLAN_NAMES = {"sub_week": "неделя", "sub_month": "месяц", "sub_3month": "3 месяца"}
MODEL_NAMES = {"base": "обычное", "premium": "премиум"}

CUSTOM_SCENE_LABEL_TEXT = "своя (текст)"
CUSTOM_SCENE_LABEL_PHOTO = "своя (фото)"

ADMIN_ONLY = "Только для админов."

ADM_STATS = (
    "📊 <b>Сегодня / 7 дней</b>\n"
    "👤 Новые пользователи: {u1} / {u7}\n"
    "🖼 Генерации обычные: {g1b} / {g7b}\n"
    "✨ Генерации премиум: {g1p} / {g7p}\n"
    "💸 Расход Runware: ${c1:.2f} / ${c7:.2f}\n"
    "⭐ Доход Stars: {s1} / {s7}\n"
    "💳 Доход Tribute: {t1} ₽ / {t7} ₽\n\n"
    "<b>Всего</b>\n"
    "👥 Пользователей: {users}, приняли правила: {accepted}\n"
    "⭐ Активных подписок: {subs}\n"
    "🖼 Генераций: {gens}\n"
    "💎 Кристалликов на руках: {crystals}\n"
    "🔗 Рефералов всего: {ref_users}"
)
ADM_USAGE_GIVE = "Формат: /give <user_id> <n>"
ADM_USAGE_SUB = "Формат: /sub <user_id> <sub_week|sub_month|sub_3month>"
ADM_USAGE_USER = "Формат: /user <user_id>"
ADM_HELP = (
    "Команды администратора:\n"
    "/admin — этот список\n"
    "/stats — статистика за сегодня и 7 дней\n"
    "/user <user_id> — карточка пользователя\n"
    "/give <user_id> <n> — начислить или списать кристаллики\n"
    "/sub <user_id> <sub_week|sub_month|sub_3month> — выдать подписку\n"
    "/block <user_id> и /unblock <user_id> — блокировка\n"
    "/actors — актёры: добавить, включить, удалить\n"
    "/scenes — сцены: добавить, включить, удалить\n"
    "/refs — реф-ссылки партнёров и статистика по ним\n"
    "/ref_add <code> <partner_user_id|-> <название> — создать реф-ссылку\n"
    "/ref_off <code> и /ref_on <code> — выключить или включить реф-ссылку\n"
    "/cancel — выйти из диалога добавления"
)
ADM_USAGE_BLOCK = "Формат: /block <user_id>"
ADM_BLOCK_OK = "Пользователь {uid} заблокирован."
ADM_UNBLOCK_OK = "Пользователь {uid} разблокирован."
ADM_USER_NOT_FOUND = "Пользователь не найден."
ADM_GIVE_OK = "Начислено {n} 💎 пользователю {uid}. Баланс: {balance}"
ADM_GIVE_INSUFFICIENT = "Нельзя списать больше, чем есть: у пользователя {balance} 💎."
ADM_SUB_OK = "Подписка {plan} пользователю {uid} до {until}"
ADM_USER_CARD = "👤 {uid} @{username}\n💎 {crystals}\n⭐ {sub}\n🖼 Генераций: {gens}\n📅 С {created}"
ADM_ACTORS = "Актёры:"
ADM_SCENES = "Сцены:"
ADM_ADD = "➕ Добавить"
ADM_BACK = "◀️ К списку"
ADM_TOGGLE = "Вкл/Выкл"
ADM_DELETE = "🗑 Удалить"
ADM_SHOW_REFS = "🖼 Фото"
ADM_ACTOR_NAME = "Имя актёра для кнопки:"
ADM_ACTOR_DESC = "Описание внешности для промпта (лучше по-английски, до 200 символов):"
ADM_ACTOR_PHOTOS = "Пришлите 2–4 фото по одному. Когда хватит, нажмите «Готово»."
ADM_ACTOR_PHOTO_OK = "Принято {n}/4."
ADM_ACTOR_NEED_MORE = "Нужно минимум 2 фото."
ADM_DONE = "✅ Готово"
ADM_ACTOR_CREATED = "Актёр «{name}» добавлен."
ADM_ADD_PHOTOS = "➕ Добавить фото"
ADM_ACTOR_NEEDS_PHOTOS = "Нужно ещё {n} фото, чтобы включить актёра."
ADM_ACTOR_MORE_PHOTOS = "Пришлите фото по одному (всего до 4). Когда хватит — «Готово»."
ADM_ACTOR_REFS_SAVED = "Сохранено: {n} фото. Актёр {state}."
ADM_ON = "включён"
ADM_OFF = "выключен"
ADM_SCENE_NAME = "Название сцены для кнопки:"
ADM_SCENE_PROMPT = "Описание сцены для промпта (по-английски, до 300 символов):"
ADM_SCENE_ORIENT = "Ориентация кадра:"
ADM_PORTRAIT = "Вертикальная"
ADM_LANDSCAPE = "Горизонтальная"
ADM_SCENE_PHOTO = "Пришлите фото места или нажмите «Без фото»."
ADM_NO_PHOTO = "Без фото"
ADM_SCENE_CREATED = "Сцена «{name}» добавлена."
ADM_ACTOR_CARD = "{name}\n{description}\nФото: {refs}/4\nАктивен: {active}"
ADM_SCENE_CARD = "{name}\n{prompt}\nОриентация: {orientation}\nФото: {photo}\nАктивна: {active}"
ADM_YES = "да"
ADM_NO = "нет"
ADM_PHOTO_PRESENT = "есть"
ADM_PHOTO_ABSENT = "нет"
ADM_USAGE_REF_ADD = "Формат: /ref_add <code> <partner_user_id|-> <название>\nКод: латиница, цифры и _ , от 3 до 32 символов."
ADM_USAGE_REF_TOGGLE = "Формат: /ref_off <code>"
ADM_REF_BAD_CODE = "Плохой код: только латиница, цифры и _ , от 3 до 32 символов."
ADM_REF_EXISTS = "Такая реф-ссылка уже есть."
ADM_REF_NOT_FOUND = "Реф-ссылка не найдена."
ADM_REF_CREATED = "Реф-ссылка «{title}» создана:\n{link}"
ADM_REFS_HEADER = "🔗 Реф-ссылки:"
ADM_REFS_EMPTY = "Реф-ссылок пока нет."
ADM_REF_OFF_MARK = "⛔ "
REF_LINE = "{mark}{code} · {title} · 👥 {users} (✅ {accepted}) · 💳 {paying} · ⭐ {stars} · ₽ {rub} · 🖼 {gens}"
ADM_REF_STATE_ON = "включена"
ADM_REF_STATE_OFF = "выключена"
ADM_REF_TOGGLED = "Реф-ссылка {code} {state}."

PARTNER_NONE = "У вас нет реф-ссылок."
PARTNER_HEADER = "🔗 Ваши реф-ссылки"
PARTNER_BLOCK = "«{title}»\n{link}\nВсего: {all_line}\n7 дней: {week_line}"
PARTNER_STATS_LINE = "👥 {users} (✅ {accepted}) · 💳 {paying} · ⭐ {stars} · ₽ {rub} · 🖼 {gens}"

ADM_TEXT_REJECTED = "Описание не прошло стоп-лист."
ADM_DELETED = "Удалено."
ADM_TOO_LONG = "Слишком длинно."

CMD_START_DESC = "Начать"
CMD_MENU_DESC = "Меню"
CMD_CANCEL_DESC = "Отмена"
CMD_ADMIN_DESC = "Команды администратора"
CMD_STATS_DESC = "Статистика"
CMD_ACTORS_DESC = "Актёры"
CMD_SCENES_DESC = "Сцены"
CMD_USER_DESC = "Карточка пользователя"
CMD_GIVE_DESC = "Начислить кристаллики"
CMD_SUB_DESC = "Выдать подписку"
CMD_BLOCK_DESC = "Заблокировать пользователя"
CMD_REFS_DESC = "Реф-ссылки и статистика"
CMD_REF_ADD_DESC = "Создать реф-ссылку"
CMD_REF_OFF_DESC = "Выключить реф-ссылку"
CMD_REF_ON_DESC = "Включить реф-ссылку"

INVOICE_DESC_PACK = "+{n} кристалликов"
INVOICE_DESC_SUB = "{days} дней подписки"
